apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5433
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres
        ports:
        - containerPort: 5433
        env:
        - name: POSTGRES_USER
          value: "edwinacevedo"
        - name: POSTGRES_PASSWORD
          value: "1182709"
        - name: POSTGRES_DB
          value: "edwinacevedo"
        resources:
          limits:
            memory: "1024Mi"  
            cpu: "1"      
          requests:
            memory: "512Mi" 
            cpu: "1"       
