version: '3'
services:
  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app

  app:
    build:
      context: ./app
    ports:
      - "8080:8080"
    environment:
      - PORT=8080 
      - DB_HOST=postgres
      - DB_USER=edwinacevedo
      - DB_PASSWORD=1182709
      - DB_NAME=edwinacevedo
      - DB_PORT=5432 
    networks:
      - mynetwork

      
networks:
  mynetwork:
    external: true

